### PR TITLE
Add NXP signing support

### PR DESCRIPTION
**Pull request by alexgg**

### CODE REVIEW

**Comment by alexgg** [comment]
Test bootstrapping of local instance:

```
curl "${SIGN_API}/bootstrap" -X POST -H "X-API-Key: ${SIGN_API_KEY}" -H "Content-type: application/json" -d '{         
  "gpg": {"name_real": "balenaOS GRUB GPG key", "name_email": "security@balena.io"},
  "certificates": {                                                                
    "pk": {"cert_id": "balenaos-pk", "subject": "/CN=balenaOS PK/"},               
    "kek": {"cert_id": "balenaos-kek", "subject": "/CN=balenaOS KEK/"},            
    "db": {"cert_id": "balenaos-db", "subject": "/CN=balenaOS db/"},               
    "kmod": {"cert_id": "balenaos-kmod", "subject": "/CN=key for signing 3rd party balenaOS kernel modules/", "key_length": 4096}
  },
  "rsa": {},
  "hab": {"hab_type": "hab"},
  "ahab": {"hab_type": "ahab"}
}'
{
  "ahab": {
    "pki_id": "44685a64661f864a8e375294de4bb825"
  },
  "certificates": {
    "db": "-----BEGIN CERTIFICATE-----\nMIIDDTCCAfWgAwIBAgIUdq1V1TMH1Zn4STmPVTr1ZhQW+/AwDQYJKoZIhvcNAQEL\nBQAwFjEUMBIGA1UEAwwLYmFsZW5hT1MgZGIwHhcNMjQwNzI2MTI1NDE0WhcNNDQw\nNzI2MTI1NDE0WjAWMRQwEgYDVQQDDAtiYWxlbmFPUyBkYjCCASIwDQYJKoZIhvcN\nAQEBBQADggEPADCCAQoCggEBAN/2U3VPEgAlma33xhW3pyXutqEq0DyjASTBobrz\noFK0/fpTpg9Dc8INZoppVin324voV2oGFrRxCby/gg/wCHlX2ko4nC3zVlE9DwWy\nvoOa4n6U1BIp5kQE3Eeda10gEYMEa4lUGOAtwgGfcX9QDSfq2aUqTjxd58l8Gq6A\neJopQiYPvKxmsW9jf+8+P8JF97AtEUgGY53ASlk29jKAd6XaSNiwgWYZB0MvHZX6\nR+SO3c1fhCk4wlwrLTrlUrTbAtrchlAemY6p8gUkg1MMhFzK8epZ+q9KfENOsQG6\nzoHXI0tE0pcEVWICCK5gSXnOZOVMOmLEz4ePKVkQCwFJsD0CAwEAAaNTMFEwHQYD\nVR0OBBYEFPtIYhm9fSs1J3J0YpweK8PnYN2kMB8GA1UdIwQYMBaAFPtIYhm9fSs1\nJ3J0YpweK8PnYN2kMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB\nAKzf8FlCcb14D0rKoEeQ8AjsAqbHF4m9glfqAZ6+bJUNNPy29Eqj9wQ/1EJnRT4U\nUekFiQH3UVNONYqQIPppLqD5InPXHlJiiwvb6QP7dK0c0DaaclZhUQqZciF98VZz\nKsx9qvi0FCMlrXCTgyA9n3PQSJiK7WuyOSRCSUb9MA37m4Nwy/eocODqBeUtB/gS\nVm0DSGLia7WvU/hypqdvNvtHEo+T8NA7KVRIaVs9FLcHD9rROkSFHLZ902HVZdjB\nTTfV9gcE9ytgVAuHrkYgDpvSi/5PN0zE7hRpmycFVINpktydEB4mpiJOidbk65UY\nHFPiPH77JgueeHeqwLbF9I4=\n-----END CERTIFICATE-----\n",
    "kek": "-----BEGIN CERTIFICATE-----\nMIIDDzCCAfegAwIBAgIUQrXuMe2CiIKWdLPhiF1WBmRjfz0wDQYJKoZIhvcNAQEL\nBQAwFzEVMBMGA1UEAwwMYmFsZW5hT1MgS0VLMB4XDTI0MDcyNjEyNTQxNFoXDTQ0\nMDcyNjEyNTQxNFowFzEVMBMGA1UEAwwMYmFsZW5hT1MgS0VLMIIBIjANBgkqhkiG\n9w0BAQEFAAOCAQ8AMIIBCgKCAQEA17rQZxoQ6onGGeHfuBAXxlcIXdnnpRp6+1wM\nCBfDw/sdpo4KrrCMayKwbNYm+7ilTc7xGzgjCdZ4IJ6srIU1CLgQJMoNqfsnJrbM\nSy950jX4cBRX54QQWfUMLNGBi5ZC0QTSTN8bfb6BFduREObfEEOog6Vii4TPdb1o\nR9Uq2y9BsY6L2QSVSuv/8rpTNCG6h9yBeSSQkMBHjmXrFLeM+HTPt6EycnnE3yv+\nce9K1zWOx9yPK5xoA8KcOCwBEj5qClFw1Q1g/wMcgZjrRqZ/LvzQ2ZeIIG3b4S5k\n9siORZwN8QvJiFO3folTlPsJ5+0ZHkdF3LjkNbHG5YFUoSnP9wIDAQABo1MwUTAd\nBgNVHQ4EFgQUGjxMdfrte/Qh0nW3rAXuTAG3SJ8wHwYDVR0jBBgwFoAUGjxMdfrt\ne/Qh0nW3rAXuTAG3SJ8wDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC\nAQEAqKoR88zkl7yC3CMcqWQczwu0tQgoKZZ7jBQkop7+gmbqg+dvPa11u2IQevff\nT9Pa4sIxRkaksuzIvXmTC2Q2kUX9s2D0IAHrkg6ESgk8TdjgD7Zjfom/fe9dTiLR\ns8sLMwI8eJqPUKgH8WlS3qKZj6/txGB/t8C/mc9Yi/jIQ03XU9Y5uE3P8HAKk7Kd\nv2PVyMBOkC1ofX614D16y/mk+Hu0MRXLrUdBjLZBY6ZMl8OkyGRiqFLwLqUPVeh+\nYaGfOF3I7tWUbyK7JRXmz11SYC/6UXLbwfj8atr1cdh6ld/EkibLVqRvfpUQjCqy\n1aHqRvuA3S/OaPBtttWL/QwdjA==\n-----END CERTIFICATE-----\n",
    "kmod": "-----BEGIN CERTIFICATE-----\nMIIFWTCCA0GgAwIBAgIUAwKTVDFsXbpPDoZnWXwScupX6ugwDQYJKoZIhvcNAQEL\nBQAwPDE6MDgGA1UEAwwxa2V5IGZvciBzaWduaW5nIDNyZCBwYXJ0eSBiYWxlbmFP\nUyBrZXJuZWwgbW9kdWxlczAeFw0yNDA3MjYxMjU0MTVaFw00NDA3MjYxMjU0MTVa\nMDwxOjA4BgNVBAMMMWtleSBmb3Igc2lnbmluZyAzcmQgcGFydHkgYmFsZW5hT1Mg\na2VybmVsIG1vZHVsZXMwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCs\nYNn4NQfkcAp8XJy3GOGPxTW4ki3vz1tocPX02pY5yz/kCj9m8D74gankgyHS/BJr\nWFZbuOVCc41PydUjWgrexLmYOQowlZDY/6kqncjgJnaSN7nH6PpozytzB7csfPFT\n1M+lbKWBxAProVqHWrSStH1+W/CNsbrlYmkHXEa3HjPrbgJoQjVO5uxmCk8QJ9xr\nRyqTWUybZJ6LjH7w7w86nxU7HqeRqA3XuROXTUenvZrV2q+QDUReRR8QmdERo6DS\nbqKvt0gaimFX/w0o7DARgd4yk9BCbylzH+A3x2Rnnge21rYFF/scfM1Bej8OhQUf\n95NfVhUf4/ihCRk+IjA4sPC3YFljJGKjbDMO0/wh+q6MURgrILt16aWmC5DIVVId\nI+Ww0HnJLUkiOpaJMpphgF3Tdh3ghGlp3DOzYmZFooOmpDbmpbiQnR4k2KbqC6kf\nqiWQRsDvWnasVAx4qt7ox7GV9j9wBFy+8o04jcur7e4VfnW/eZt8NW9XU0j0HAA3\nPuj0IoLE2Io2G407iFTZURs4VoUnGz9fuVmk673DB7QA28lehD8rn500L1IanCxz\naohKzGN5OFRCBuOiI/UmeKIlfXGOzLTWl4mGCxcp2j4b4jXO0p2DV4XpEIpfU/f7\n5x0t6HtNEpIvFgzkijUp8ePdmfuIpY+sRDVgdyARGQIDAQABo1MwUTAdBgNVHQ4E\nFgQU6Ov97wnEmS+z3Q8bqUcHGLvSOo4wHwYDVR0jBBgwFoAU6Ov97wnEmS+z3Q8b\nqUcHGLvSOo4wDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAjhKB\n4E/7ozxZ7OXgIiLQTNj51+LhgAJPSifBy4TKCXlO8lmVNZpTFzyAiGr8PVCgQGwJ\ncG/Cztiuz31v13i/qeRR8ZP3XTjnjk95C5TmCmDRGH/W3Fl4bjq3t94wMk8ppQBv\nfhuWhELuHOZrresW4q5m105FuUEkv6JLy+IrelMRDNfPzJh3/Tpe+HbAj/lz8Iyj\nQTASw/l/UgtGLHJuPnhWmciTt4mL5LVGZjzuBRgZhl7e7LlSPraXdvCtBQTKS8cQ\ncXpozkZl2fhaQeGMkDM6WiocUYbZhuQcTljV1DpMUMKkFm7C8pka9c9QPA63Hvw0\nMa1fUOcfxxUEGGmf6GPiPyexzpSt1lMjCtpvKMvsj1IJm115kqoIHg7PrLDG8RbH\nUxxpW/F0cso6beJUunj0+nFshOusbbAXWVN+EiVU0NLc4uAsgsZ7KNy/NeTXCu0m\na9xP0TDpxKjKT36VdcSXkHR90y9bdduhi1V52nMPmNgRJrs8q3GtyAJuY+7tglMG\ncF/nbJsY3kq23I/ONt/VAAfds85KvaOGg0YH4MkYKqLMtjpOcsMyDOWMTn0vnObX\nfF520FYw/pOdzs5Djp65KR97GClWQlFrPXi7t9f5h6tYr4/mq25HB+39WoGdRap0\nyNpcXdrK4afq2FyjirSJ5WD67G0ZpNeXKU/SSDw=\n-----END CERTIFICATE-----\n",
    "pk": "-----BEGIN CERTIFICATE-----\nMIIDDTCCAfWgAwIBAgIUBDMW4Fzr6XwKJyDrlbfLudGAyfcwDQYJKoZIhvcNAQEL\nBQAwFjEUMBIGA1UEAwwLYmFsZW5hT1MgUEswHhcNMjQwNzI2MTI1NDE0WhcNNDQw\nNzI2MTI1NDE0WjAWMRQwEgYDVQQDDAtiYWxlbmFPUyBQSzCCASIwDQYJKoZIhvcN\nAQEBBQADggEPADCCAQoCggEBAJoZg3dxyuVamgKOvN6YCmotNvFHXCTwgV8OYCit\n8PgzLXunr5F/+Vr10bt//arUHK7Ve0bnNKDlCjMnKhoYVjpqvzIAZLwLKCnCw4Iz\ns16w2L0r4Xb+KH7hWJejC7OuOjqLLEASGySzizAxTcNLU3gsKFz3PhGKz9+gjQqn\nSiSwHZjiCCbvcD5qCWea4cSD5lFIF8dkhpUor/RCXC1JvLTMVELz2LeQviUmETAo\nSx0Y8bawi53C54KiwF1bciqK7GJ0C/tI7AcHqVfh+z1fHns4vNX76/pevB6h/pSv\nPjuUZF8OmH+RpR8TGDmTjrKAzOlujiLaUsm/Zt3588hpl1UCAwEAAaNTMFEwHQYD\nVR0OBBYEFPq1dLp8esWHxTu88v1HF9kNuSJ9MB8GA1UdIwQYMBaAFPq1dLp8esWH\nxTu88v1HF9kNuSJ9MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB\nAF1Q3hHzCxJi//BW9uON7vKdYbRHENlrYWfqP9rdzC+xl/WtDQ0bIJL0eOwW8tli\nQULS1t3KsBcSwUcw18oSnwEchBfVpwDfnvdEBm3vvhrFF5RGQIbHfrd9y91EtbLI\nDoyaMCpJuALi1z+VFCdG+dBlAu9ECIO97vmC95HkRfe/lYp6rmoFD3hf1RAyQlgu\nwzF9rI9/0iMN+0zvauk8orAqPmaKbvBDz8cn2MjipGLdg3wAy9XDYseR4zkX2k2o\nGKY/G9JNJGvlb1m12RYNTdKTOdxWkBFzvvZbhKXW6Lq4lY5AZ93eJa8Kv3jRpKoS\nY5pWOnPLO34LSlaFs0q3seA=\n-----END CERTIFICATE-----\n"
  },
  "gpg": {
    "fingerprint": "1A75F866805EDBD8CB82ECB5C5A4A852E2432324"
  },
  "hab": {
    "pki_id": "3595d1ac548998804323c78071256924"
  },
  "rsa": {
    "fingerprint": "ba84544c65306f65059b0109767504f3"
  }
}
```

Logs:
```
 balenasign  INFO:app:g_alex_gonzalez2 attempting to bootstrap signing material
 balenasign  Generating a RSA private key
 balenasign  .+++++
 balenasign  ..................+++++
 balenasign  writing new private key to '/opt/balena/balenasign/secrets/x509/balenaos-pk.key'
 balenasign  -----
 balenasign  INFO:cert:g_alex_gonzalez2 successfully generated a new certificate balenaos-pk
 balenasign  Generating a RSA private key
 balenasign  ..............+++++
 balenasign  ..................+++++
 balenasign  writing new private key to '/opt/balena/balenasign/secrets/x509/balenaos-kek.key'
 balenasign  -----
 balenasign  INFO:cert:g_alex_gonzalez2 successfully generated a new certificate balenaos-kek
 balenasign  Generating a RSA private key
 balenasign  .............+++++
 balenasign  ...........................+++++
 balenasign  writing new private key to '/opt/balena/balenasign/secrets/x509/balenaos-db.key'
 balenasign  -----
 balenasign  INFO:cert:g_alex_gonzalez2 successfully generated a new certificate balenaos-db
 balenasign  Generating a RSA private key
 balenasign  ......................................................................................................................................................................................................++++
 balenasign  ...........................................................................................................................................................................................++++
 balenasign  writing new private key to '/opt/balena/balenasign/secrets/x509/balenaos-kmod.key'
 balenasign  -----
 balenasign  INFO:cert:g_alex_gonzalez2 successfully generated a new certificate balenaos-kmod
 balenasign  Timestamp is 2024-7-26 12:54:15
 balenasign  Authentication Payload size 869
 balenasign  Signature of size 1175
 balenasign  Signature at: 40
 balenasign  Timestamp is 2024-7-26 12:54:15
 balenasign  Authentication Payload size 873
 balenasign  Signature of size 1175
 balenasign  Signature at: 40
 balenasign  Timestamp is 2024-7-26 12:54:15
 balenasign  Authentication Payload size 869
 balenasign  Signature of size 1175
 balenasign  Signature at: 40
 balenasign  INFO:gpg:g_alex_gonzalez2 successfully generated a new gpg key 1A75F866805EDBD8CB82ECB5C5A4A852E2432324
 balenasign  INFO:rsa:g_alex_gonzalez2 successfully generated a new RSA key ba84544c65306f65059b0109767504f3
 balenasign  INFO:nxp:Generating hab PKI tree
 balenasign  INFO:nxp:Generating hab SRKS table
 balenasign  INFO:nxp:g_alex_gonzalez2 successfully generated a new hab PKI tree 3595d1ac548998804323c78071256924
 balenasign  INFO:nxp:Generating ahab PKI tree
 balenasign  INFO:nxp:Generating ahab SRKS table
 balenasign  INFO:nxp:g_alex_gonzalez2 successfully generated a new ahab PKI tree 44685a64661f864a8e375294de4bb825
 balenasign  INFO:app:g_alex_gonzalez2 bootstrapped signing service
```

**Comment by alexgg** [comment]
Manual tests:

- [ ] Bootstrapping
- [ ] Exporting
- [ ] Importing
- Key creation:
  - [ ] RSA
  - [ ] GPG
  - [ ] SB Certificates
  - [ ] IMX
- Key retrieval:
  - [ ] RSA
  - [ ] GPG
  - [ ] IMX
  - [ ] IMX efuses
  - [ ] SB certs
  - [ ] SB KEK
  - [ ] SB PK
  - [ ] SB DB
  - [ ] SB DBX
  - Signing:
    - [ ] x86_64
    - [ ] CM4
    - [ ] IMX8

**Review by mtoman — COMMENTED** [review]
No major objections. The deps update works & does not seem to break anything that already works. Is there an easy way for me to test the NXP bits?

One general nitpick - I would prefer `os.path.join` over format strings for building file paths, but it's not worth redoing the whole PR just to fix this.

One thing that needs fixing is the demo bootstrap requests in README, but you already have a working example in a comment above, just copy it out and lgtm.

**Comment by mtoman** [comment]
lgtm

**Comment by alexgg** [comment]
@mtoman retrieving keys for i.MX is easy:
```
curl --fail "${SIGN_API}/imx/pkis"
{
  "pkis": [
    "8c66f2dd817c2ed90a5c0942d6a0b10d",
    "4450647f3cf4d219291ad1cbb4579cb6"
  ]
}

curl --fail "${SIGN_API}/imx/efuses/8c66f2dd817c2ed90a5c0942d6a0b10d"
{
  "efuses": "cktmcvXNcdIymHViyXWFih01GYh3s1rOCoiLPSXwnXmcWKV5wk2e2RLupGsCsusF0PgQUWe5+bvbZG3Ps1td8w=="
}

curl --fail "${SIGN_API}/imx/efuses/4450647f3cf4d219291ad1cbb4579cb6"
{
  "efuses": "VM5/vCG1DZuWMSkijUR9/FWRYOeAi3PxbXGjHnfIeCo="
}
```
i.MX signing is not easy as it needs a CSF descriptor that is generated based on the payload. The best way would be building https://github.com/balena-os/balena-iot-gate-imx8/tree/alexgg/hab against a local signing server and seeing the logs.

**Pull request merged**
